const DATA=[
{org:'education',institution:'I.E. Bertha Suttner',site:'Administración y Primaria',city:'Cartagena',zone:'NELSON MANDELA 1',type:'Sede',people:396,date:'09/03/2023',internet:'Sí',provider:'Tigo',quality:'Regular'},
{org:'education',institution:'I.E. Colombo Holandés',site:'Única',city:'Cartagena',zone:'NELSON MANDELA 1',type:'Principal',people:350,date:'17/03/2023',internet:'Sí',provider:'Movistar',quality:'Regular'},
{org:'education',institution:'I.E. Alto del Rosario',site:'Principal',city:'Sincelejo',zone:'SINCELEJO',type:'Principal',people:1100,date:'30/09/2025',internet:'Sí',provider:'Ministerio de Educación',quality:'Regular'},
{org:'education',institution:'I.E. Alto del Rosario',site:'San Roque',city:'Sincelejo',zone:'SINCELEJO',type:'Sede',people:469,date:'30/09/2025',internet:'Sí',provider:'Ministerio de Educación',quality:'Regular'},
{org:'education',institution:'I.E. Crisanto Luque',site:'Papayal',city:'Turbaco',zone:'TURBACO',type:'Sede',people:180,date:'01/12/2025',internet:'Sí',provider:'Gobernación',quality:'Regular'},
{org:'education',institution:'I.E. Victoria Manzur',site:'El Paraíso',city:'Montería',zone:'MONTERÍA',type:'Sede',people:755,date:'18/12/2025',internet:'Sí',provider:'Alcaldía',quality:'Regular'},
{org:'education',institution:'I.E. Dulce Nombre de Jesús',site:'La Pollita',city:'Sincelejo',zone:'SINCELEJO',type:'Sede',people:246,date:'01/12/2025',internet:'Sí',provider:'No sabe',quality:'Regular'},
{org:'education',institution:'I.E.D. Ondas del Caribe',site:'Altos de Villa Concha',city:'Santa Marta',zone:'SANTA FE-BASTIDAS',type:'Sede',people:350,date:'En despliegue',internet:'No',provider:'No sabe',quality:'No sabe'},
{org:'foundation',institution:'Granito de Paz',site:'Centro Productivo',city:'Cartagena',zone:'OLAYA 1',type:'Sede',people:0,date:'25/09/2023',internet:'No',provider:'No sabe',quality:'No sabe'},
{org:'foundation',institution:'Fundación Madre Elfride',site:'Casa de Hermanas',city:'Cartagena',zone:'NELSON MANDELA 1',type:'Sede',people:0,date:'09/03/2023',internet:'Sí',provider:'Tigo',quality:'Regular'},
{org:'foundation',institution:'Fundación Madre Elfride',site:'Biblioteca Infantil',city:'Cartagena',zone:'NELSON MANDELA 1',type:'Sede',people:367,date:'09/03/2023',internet:'Sí',provider:'Tigo',quality:'Bueno'}
];
const TOTALS={education:{sites:183,unique:94,people:140854,cities:6},foundation:{sites:7,unique:6,people:1108,cities:1}};
const CITY_TOTALS={education:[['Cartagena',114,89037],['Santa Marta',20,15240],['Barranquilla',15,12410],['Sincelejo',14,10765],['Turbaco',11,8920],['Montería',9,4482]],foundation:[['Cartagena',7,1108]]};
const HISTORY={education:[[2023,20,11155],[2024,69,55734],[2025,179,138676],[2026,183,140854]],foundation:[[2023,6,1108],[2024,6,1108],[2025,7,1108],[2026,7,1108]]};
let view='schools';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], fmt=n=>new Intl.NumberFormat('es-CO').format(n);
const filters={org:$('#orgFilter'),city:$('#cityFilter'),zone:$('#zoneFilter'),site:$('#siteFilter'),size:$('#sizeFilter'),internet:$('#internetFilter')};
function unique(key,org){return [...new Set(DATA.filter(d=>d.org===org).map(d=>d[key]))].sort()}
function fillSelect(el,values,first){el.innerHTML=`<option value="all">${first}</option>`+values.map(v=>`<option>${v}</option>`).join('')}
function syncOptions(){fillSelect(filters.city,unique('city',filters.org.value),'Todas');fillSelect(filters.zone,unique('zone',filters.org.value),'Todas')}
function inSize(n,v){return v==='all'||(v==='0-200'&&n<=200)||(v==='201-500'&&n>200&&n<=500)||(v==='501-1000'&&n>500&&n<=1000)||(v==='1001+'&&n>1000)}
function rows(){const q=$('#searchInput').value.toLowerCase();return DATA.filter(d=>d.org===filters.org.value&&(filters.city.value==='all'||d.city===filters.city.value)&&(filters.zone.value==='all'||d.zone===filters.zone.value)&&(filters.site.value==='all'||d.type===filters.site.value)&&(filters.internet.value==='all'||d.internet===filters.internet.value)&&inSize(d.people,filters.size.value)&&(!q||`${d.institution} ${d.site}`.toLowerCase().includes(q)))}
function renderKpis(){const org=filters.org.value,t=TOTALS[org],foundation=org==='foundation';$('#kpis').innerHTML=`<article class="kpi primary"><span>${foundation?'Centros de fundaciones':'Sedes educativas'} conectados</span><strong>${fmt(t.sites)}</strong><small>Conectividad gratuita activa</small></article><article class="kpi"><span>${foundation?'Fundaciones':'Instituciones'} únicas</span><strong>${fmt(t.unique)}</strong><small>Organizaciones beneficiadas</small></article><article class="kpi"><span>${foundation?'Beneficiarios registrados':'Alumnos conectados'}</span><strong>${fmt(t.people)}</strong><small>Impacto acumulado</small></article><article class="kpi accent"><span>Ciudades con presencia</span><strong>${t.cities}</strong><small>${foundation?'Fundaciones':'Instituciones educativas'}</small></article>`}
function renderGrowth(){const org=filters.org.value,metric=view==='schools'?1:2,arr=HISTORY[org],max=Math.max(...arr.map(x=>x[metric]));$('#growthTitle').textContent=`Crecimiento de ${view==='schools'?(org==='foundation'?'fundaciones':'sedes'):(org==='foundation'?'beneficiarios':'alumnos')}`;$('#growthChart').innerHTML=arr.map(x=>`<div class="growth-col"><b>${fmt(x[metric])}</b><i style="height:${Math.max(8,x[metric]/max*165)}px"></i><small>${x[0]}</small></div>`).join('')}
function renderCities(){const org=filters.org.value,metric=view==='schools'?1:2,arr=CITY_TOTALS[org].filter(x=>filters.city.value==='all'||x[0]===filters.city.value),max=Math.max(1,...arr.map(x=>x[metric]));$('#cityChart').innerHTML=arr.map(x=>`<div class="bar-row"><span>${x[0]}</span><div class="track"><i style="width:${x[metric]/max*100}%"></i></div><b>${fmt(x[metric])}</b></div>`).join('')}
function renderConnectivity(){const rs=DATA.filter(d=>d.org===filters.org.value),yes=rs.filter(d=>d.internet==='Sí').length,no=rs.length-yes,pct=Math.round(yes/Math.max(1,rs.length)*100);$('#internetSummary').innerHTML=`<div class="donut" style="background:conic-gradient(var(--green) 0 ${pct}%,var(--yellow) ${pct}% 100%)"></div><div class="donut-labels"><div><i class="dot" style="background:var(--green)"></i>Tenían internet · ${yes}</div><div><i class="dot" style="background:var(--yellow)"></i>No tenían · ${no}</div></div>`;const group=(key)=>Object.entries(rs.reduce((a,d)=>(a[d[key]]=(a[d[key]]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]);const providers=group('provider').slice(0,5),pm=Math.max(...providers.map(x=>x[1]));$('#providerChart').innerHTML=providers.map(x=>`<div class="provider-item"><span>${x[0]}</span><div class="track"><i style="width:${x[1]/pm*100}%"></i></div><b>${x[1]}</b></div>`).join('');$('#qualityChart').innerHTML=group('quality').map(x=>`<div class="quality"><b>${x[1]}</b><small>${x[0]}</small></div>`).join('')}
function renderTable(){const org=filters.org.value,foundation=org==='foundation';$('#tableTitle').textContent=foundation?'Fundaciones conectadas':'Instituciones educativas conectadas';$('#peopleHeader').textContent=foundation?'Beneficiarios':'Alumnos';const rs=rows();$('#recordsBody').innerHTML=rs.length?rs.map(d=>`<tr><td><strong>${d.institution}</strong><small>${d.site}</small></td><td>${d.city}</td><td>${d.zone}</td><td><span class="pill">${d.type}</span></td><td>${d.people?fmt(d.people):'No aplica'}</td><td>${d.date}</td><td><span class="bool ${d.internet==='No'?'no':''}">${d.internet}</span></td><td>${d.provider}</td></tr>`).join(''):`<tr><td colspan="8" class="empty">No hay resultados para estos filtros.</td></tr>`}
function render(){renderKpis();renderGrowth();renderCities();renderConnectivity();renderTable()}
Object.values(filters).forEach(el=>el.addEventListener('change',()=>{if(el===filters.org)syncOptions();render()}));$('#searchInput').addEventListener('input',renderTable);$('#clearFilters').addEventListener('click',()=>{filters.org.value='education';syncOptions();filters.site.value=filters.size.value=filters.internet.value='all';$('#searchInput').value='';render()});$$('.view-switch button').forEach(b=>b.addEventListener('click',()=>{$$('.view-switch button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()}));syncOptions();render();
